### ISSUE TITLE
Docs: Add permissions needed to run the action to README

### ISSUE THREAD

**Issue by stevenengland** [aslafy-z/conventional-pr-title-action#260]
Hi,

if a repo uses a resticted access it is neccessary to explicitely add permissions to use this action. Reading the code and from a first try on a private repo I guess in your case it is:

`statuses: write`

```
jobs:
  pr_title_check:
    permissions:
      statuses: write # <-- here
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        with:
          preset: conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
